G2-250 Testing and error checking

diff --git a/builtin/common/pallet2jack b/builtin/common/pallet2jack
--- a/builtin/common/pallet2jack
+++ b/builtin/common/pallet2jack
@@ -38,7 +38,12 @@ case ${WAREHOUSE} in
 	*)
 	pushd ${SELF_DIR} > /dev/null 2>&1
 		JACKFILE=$(mktemp)
+		set +e
 		${SELF_DIR}/cache ${SELF_DIR}/findjacks ${WAREHOUSE} ${PALLET} ${VERSION} > ${JACKFILE}
+		set -e
+		if [ ! -f ${JACKFILE} ]; then
+			fail "Could not find suitable jack for pallet \"${WAREHOUSE}\" \"${PALLET}\" \"${VERSION}\" (couldn't even search for jacks)"
+		fi
 		JACKCOUNT=$(wc -l ${JACKFILE} | cut -f 1 -d ' ')
 		if [[ ${JACKCOUNT} -ne 1 ]]; then
 			fail "Could not find suitable jack for pallet \"${WAREHOUSE}\" \"${PALLET}\" \"${VERSION}\" (found ${JACKCOUNT} jacks)"
